from selenium.webdriver.common.by import By

LOGIN_REG_BUTTON = (By.XPATH, "//button[contains(text(), 'Вход и регистрация')]") 
CREATE_AD_BUTTON = (By.XPATH, "//button[contains(text(), 'Разместить объявление')]")
MODAL_TITLE = (By.XPATH, "//h2[contains(text(), 'Войти')]")
NO_ACCOUNT_BUTTON = (By.XPATH, "//button[contains(text(), 'Нет аккаунта')]")
AUTH_MODAL_TITLE = (By.XPATH, "//button[contains(text(), 'Войти')]")
REG_EMAIL_INPUT = (By.NAME, "email") 
REG_PASSWORD_INPUT = (By.NAME, "password")
REG_CONFIRM_PASSWORD_INPUT = (By.NAME, "submitPassword")
CREATE_ACCOUNT_BUTTON = (By.XPATH, "//button[contains(text(), 'Создать аккаунт')]")
AUTH_EMAIL_INPUT = (By.NAME, "email") 
AUTH_PASSWORD_INPUT = (By.NAME, "password") 
LOGIN_BUTTON = (By.XPATH, "//button[contains(text(), 'Войти')]")
ERROR_FIELD = (By.CLASS_NAME, "input_inputError__fLUP9") 
ERROR_MESSAGE = (By.CLASS_NAME, "input_span__yWPqB") 
USER_AVATAR = (By.CLASS_NAME, "circleSmall")
USER_NAME = (By.CLASS_NAME, "profileText")
LOGOUT_BUTTON = (By.XPATH, "//button[contains(text(), 'Выйти')]")
AUTH_REQUIRED_MODAL = (By.XPATH, "//h1[contains(text(), 'Чтобы разместить объявление, авторизуйтесь')]")
AD_TITLE_INPUT = (By.NAME, "name")
AD_DESCRIPTION_INPUT = (By.NAME, "description")
AD_PRICE_INPUT = (By.NAME, "price")
AD_CATEGORY_DROPDOWN = (By.NAME, "category")
AD_CITY_DROPDOWN = (By.NAME, "city")
AD_CONDITION_RADIO_NEW = (By.XPATH, "//input[@value='Новый']")
AD_CONDITION_RADIO_USED = (By.XPATH, "//input[@value='Б/У']") 
PUBLISH_BUTTON = (By.XPATH, "//button[contains(text(), 'Опубликовать')]")
PROFILE_LINK = (By.XPATH, "//a[contains(text(), 'Профиль')]")
MY_ADS_SECTION = (By.XPATH, "//h1[contains(text(), 'Мои объявления')]")
FIRST_AD_IN_PROFILE = (By.XPATH, "//div[@class='my-ads-list']//div[1]")